ots/urls.py
from django.urls import path
from OTS import views
app_name = 'OTS'

urlpatterns = [
    path('',views.welcome,name='welcome'),
    # path('new-candidate',views.candidateRegistrationForm,name='registration-Form'),
    path('store-candidate',views.candidateRegistration,name='storeCandidate'),
    path('login',views.loginView,name='login'),
    path('home',views.candidateHome),
    path('testpaper',views.testpaper),
    path('calculateresult',views.calculateTestResult),
    path('testhistory',views.testResultHistory),
    path('showtestresult',views.showTestresult),
    path('logoutview',views.logoutView),

]

ots/models.py
from django.db import models

class Candidate(models.Model):
    username = models.CharField(primary_key=True, max_length=20)
    password = models.CharField(null=False, max_length=20)   
    name = models.CharField(null=False, max_length=30)
    test_attempted = models.IntegerField()
    points = models.FloatField()

class Question(models.Model):
    qid=models.BigAutoField(primary_key=True,auto_created=True)
    que=models.TextField()
    a=models.CharField(max_length=255)
    b=models.CharField(max_length=255)
    c=models.CharField(max_length=255)
    d=models.CharField(max_length=255)
    ans=models.CharField(max_length=2)
class Result(models.Model):
    Resultid=models.BigAutoField(primary_key=True,auto_created=True)
    username=models.ForeignKey(Candidate,on_delete=models.CASCADE)
    date=models.DateField(auto_now=True)
    time=models.TimeField(auto_now=True)
    attempt=models.IntegerField()
    right=models.IntegerField()
    wrong=models.IntegerField()
    points=models.FloatField()

ots/views.py
from django.shortcuts import render
from django.template import loader # Import loader to load templates on web pages on  browser
from django.http import HttpResponse,HttpResponseRedirect # Import HttpResponse to send response to browser
from django.urls import reverse # Import reverse to redirect to a different URL
from OTS.models import *

def welcome(request):
    templates = loader.get_template('welcome.html')
    return HttpResponse(templates.render())
# def candidateRegistrationForm(request):
#     templates = loader.get_template('registration_form.html')
#     return HttpResponse(templates.render())
def candidateRegistration(request):
    pass
def loginView(request):
    pass
def candidateHome(request):
    pass
def testpaper(request):
     pass
def calculateTestResult(request):
    pass
def testResultHistory(request):
    pass
def showTestresult(request):
    pass
def logoutView(request):
    pass

ots/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="top">
        <div class="sitename">
            <h1>Online Testing System</h1>
        </div>
        <div class="menu">
            {% block top %}{% endblock %}
        </div>
    </div>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

ots/templates/registration_from.html
{% extends 'main.html' %}
{% load static %}

{% block title %} ots registration Form {% endblock title %}
{% block top %}

<a href="{% url 'OTS:welcome' %}">Home</a>
<a href="{% url 'OTS:login' %}">login</a>
{% endblock %}
{% block content %}
<div class="all-forms">
    <form action="{% url 'OTS:storeCandidate' %}" method="post">
        {% csrf_token %}
        <h1>Registration Form</h1>
        <label for="name">username</label>
        <input type="text" name="username">
        <label for="password">password</label>
        <input type="password" name="password">
        <label for="name">name</label>
        <input type="text" name="name">


        <button type="submit">submit</button>
        <button type="reset">clear</button>
    </form>
    <p>Already have an account? <a href="{% url 'OTS:login' %}">Login</a></p>
</div>
{% endblock %}

ots/templates/welcome.html
{% extends 'main.html' %}

{% block title %} welcome to online testing system {% endblock title %}
{% block top %}
<a href="{% url 'OTS:registrationForm' %}">sigup</a>
<a href="{% url 'OTS:login' %}">login</a>
{% endblock %}
{% block content %}
<p>welcome online system</p>
{% endblock %}